CREATE EXTENSION IF NOT EXISTS pgcrypto;

ALTER TABLE app RENAME TO apps;

ALTER TABLE apps
    DROP CONSTRAINT app_pkey,
    ALTER COLUMN id DROP DEFAULT,
    ALTER COLUMN id TYPE UUID USING gen_random_uuid(),
    ADD PRIMARY KEY (id);

ALTER TABLE apps
    ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT now();
